[versions]
android-plugin = "8.13.2"
kotlin-plugin = "2.2.21"
track-plugin = "1.1.4"

androidx-junit = "1.3.0"
androidx-espresso = "3.7.0"
androidx-appcompat = "1.7.1"
androidx-activity = "1.12.1"
androidx-lifecycle = "2.10.0"
androidx-exifinterface = "1.4.2"
androidx-compose-bom = "2025.12.00"

kotlinx-coroutines = "1.10.2"
kotlinx-collections-immutable = "0.4.0"

junit = "4.13.2"
coil = "3.3.0"
tencent-imsdk = "8.8.7359"
squareup-okHttp = "5.3.2"
leavesczy-matisse = "2.2.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-plugin" }
leavesczy-track = { id = "io.github.leavesczy.track", version.ref = "track-plugin" }

chat-android-application = { id = "chat.android.application" }
chat-android-library = { id = "chat.android.library" }
chat-android-compose = { id = "chat.android.compose" }
chat-kotlin-parcelize = { id = "chat.kotlin.parcelize" }
chat-leavesczy-track = { id = "chat.leavesczy.track" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
leavesczy-track-gradle = { module = "io.github.leavesczy:track", version.ref = "track-plugin" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

androidx-compose-bom = { module = "androidx.compose:compose-bom-beta", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

junit = { module = "junit:junit", version.ref = "junit" }
tencent-imsdk = { module = "com.tencent.imsdk:imsdk-plus", version.ref = "tencent-imsdk" }
squareup-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okHttp" }
leavesczy-matisse = { module = "io.github.leavesczy:matisse", version.ref = "leavesczy-matisse" }